from typing import List, Dict
import re

# ── Genre mood map (derived from genre names, no Spotify audio-features API) ──
GENRE_MOOD = {
    "hip-hop": {"energy": 0.80, "valence": 0.60, "dance": 0.82, "mainstream": 0.75},
    "rap": {"energy": 0.78, "valence": 0.55, "dance": 0.80, "mainstream": 0.72},
    "trap": {"energy": 0.82, "valence": 0.48, "dance": 0.78, "mainstream": 0.65},
    "pop": {"energy": 0.72, "valence": 0.70, "dance": 0.75, "mainstream": 0.90},
    "dance pop": {"energy": 0.78, "valence": 0.72, "dance": 0.83, "mainstream": 0.88},
    "r&b": {"energy": 0.62, "valence": 0.60, "dance": 0.74, "mainstream": 0.70},
    "soul": {"energy": 0.58, "valence": 0.65, "dance": 0.68, "mainstream": 0.55},
    "rock": {"energy": 0.82, "valence": 0.50, "dance": 0.55, "mainstream": 0.65},
    "indie": {"energy": 0.60, "valence": 0.55, "dance": 0.58, "mainstream": 0.25},
    "alternative": {"energy": 0.65, "valence": 0.48, "dance": 0.55, "mainstream": 0.35},
    "electronic": {"energy": 0.85, "valence": 0.62, "dance": 0.85, "mainstream": 0.60},
    "edm": {"energy": 0.88, "valence": 0.65, "dance": 0.88, "mainstream": 0.72},
    "classical": {"energy": 0.28, "valence": 0.55, "dance": 0.25, "mainstream": 0.30},
    "jazz": {"energy": 0.42, "valence": 0.62, "dance": 0.52, "mainstream": 0.20},
    "metal": {"energy": 0.95, "valence": 0.35, "dance": 0.42, "mainstream": 0.30},
    "folk": {"energy": 0.38, "valence": 0.58, "dance": 0.40, "mainstream": 0.20},
    "country": {"energy": 0.65, "valence": 0.68, "dance": 0.62, "mainstream": 0.60},
    "latin": {"energy": 0.78, "valence": 0.75, "dance": 0.88, "mainstream": 0.75},
    "reggaeton": {"energy": 0.80, "valence": 0.72, "dance": 0.88, "mainstream": 0.70},
    "afrobeats": {"energy": 0.78, "valence": 0.76, "dance": 0.86, "mainstream": 0.55},
    "k-pop": {"energy": 0.75, "valence": 0.72, "dance": 0.78, "mainstream": 0.70},
    "bollywood": {"energy": 0.72, "valence": 0.70, "dance": 0.74, "mainstream": 0.65},
    "tamil": {"energy": 0.70, "valence": 0.68, "dance": 0.72, "mainstream": 0.55},
    "telugu": {"energy": 0.70, "valence": 0.68, "dance": 0.72, "mainstream": 0.52},
    "hindi": {"energy": 0.68, "valence": 0.66, "dance": 0.70, "mainstream": 0.60},
    "lo-fi": {"energy": 0.30, "valence": 0.52, "dance": 0.48, "mainstream": 0.45},
    "ambient": {"energy": 0.22, "valence": 0.50, "dance": 0.28, "mainstream": 0.15},
    "punk": {"energy": 0.90, "valence": 0.45, "dance": 0.52, "mainstream": 0.30},
    "blues": {"energy": 0.48, "valence": 0.42, "dance": 0.50, "mainstream": 0.20},
    "sad": {"energy": 0.35, "valence": 0.25, "dance": 0.35, "mainstream": 0.50},
    "chill": {"energy": 0.32, "valence": 0.58, "dance": 0.45, "mainstream": 0.50},
    "workout": {"energy": 0.90, "valence": 0.62, "dance": 0.75, "mainstream": 0.60},
    "devotional": {"energy": 0.45, "valence": 0.72, "dance": 0.40, "mainstream": 0.30},
    "film": {"energy": 0.60, "valence": 0.60, "dance": 0.58, "mainstream": 0.55},
}

# ── Funny personality types ──
PERSONALITY_TYPES = {
    "😭 The Crier": "Your playlist is basically a therapy session. You listen to sad songs at 2am and call it self-care.",
    "🏋️ The Gym Rat": "Every song you own could feature in a gym montage. Do you even own any slow songs?",
    "👴 The Boomer": "Your music taste is frozen in a specific decade. You peaked musically and you know it.",
    "🌿 The Pretentious One": "Nobody has heard of your artists. That's the point, isn't it?",
    "🎭 The Chameleon": "Different genre every week. You have no idea who you are and your playlist proves it.",
    "💘 The Romantic": "Every song is a love story. You're either deeply in love or deeply in denial.",
    "🥷 The Ghost": "You barely listen but when you do, the choices are... interesting.",
    "🎰 The Randomizer": "No pattern whatsoever. A playlist generated by throwing darts at a Spotify wall.",
    "😤 The Obsessive": "One artist. Constantly. Repeatedly. Exclusively. Please seek help.",
    "🤡 The Mainstream": "You only listen to what Spotify tells you to. A walking algorithm.",
    "🔥 The Hype Beast": "Only bangers. Only energy. You would give yourself a headache at a library.",
    "😴 The Background Listener": "Your music is so chill it barely qualifies as music. Elevator banger.",
}

# ── Squad awards ──
SQUAD_AWARDS = {
    "👑 Music Overlord": "Highest overall taste score in the squad",
    "💀 Needs Therapy": "Most sad/depressing music detected",
    "🤡 Spotify's Puppet": "Most mainstream listener",
    "🧅 Too Cool For This": "Most obscure/underground taste",
    "⏰ Stuck in Time": "Oldest music taste in the squad",
    "🔁 One-Trick Pony": "Most obsessed with a single artist",
    "🌍 World Citizen": "Most genre diversity",
    "🔥 Hype Beast": "Highest energy music",
    "😴 Background Music": "Most chill/ambient taste",
    "🎭 Most Chaotic": "Least consistent music taste",
}


def derive_mood_from_genres(genres: List[str]) -> Dict[str, float]:
    """Derive mood scores purely from user's genre list."""
    if not genres:
        return {"energy": 0.60, "valence": 0.55, "dance": 0.60, "mainstream": 0.55}

    energy_vals, valence_vals, dance_vals, mainstream_vals = [], [], [], []

    for genre in genres:
        gl = genre.lower()
        for key, mood in GENRE_MOOD.items():
            if key in gl:
                energy_vals.append(mood["energy"])
                valence_vals.append(mood["valence"])
                dance_vals.append(mood["dance"])
                mainstream_vals.append(mood["mainstream"])
                break

    if not energy_vals:
        return {"energy": 0.60, "valence": 0.55, "dance": 0.60, "mainstream": 0.55}

    return {
        "energy":      round(sum(energy_vals)      / len(energy_vals),      3),
        "valence":     round(sum(valence_vals)      / len(valence_vals),     3),
        "dance":       round(sum(dance_vals)        / len(dance_vals),       3),
        "mainstream":  round(sum(mainstream_vals)   / len(mainstream_vals),  3),
    }


def get_personality_type(
    mood: Dict[str, float],
    top_artists: List[str],
    genres: List[str],
) -> str:
    energy      = mood.get("energy",     0.5)
    valence     = mood.get("valence",    0.5)
    mainstream  = mood.get("mainstream", 0.5)

    # Check for one-artist obsession
    if top_artists and len(set(top_artists[:5])) <= 2:
        return "😤 The Obsessive"

    if valence < 0.38:
        return "😭 The Crier"
    if energy > 0.82:
        return "🔥 The Hype Beast"
    if energy < 0.30:
        return "😴 The Background Listener"
    if mainstream > 0.82:
        return "🤡 The Mainstream"
    if mainstream < 0.28:
        return "🌿 The Pretentious One"
    if energy > 0.75 and valence < 0.45:
        return "🏋️ The Gym Rat"
    if valence > 0.72:
        return "💘 The Romantic"

    genre_str = " ".join(genres).lower()
    decade_genres = ["oldies", "classic", "70s", "80s", "90s", "retro", "vintage"]
    if any(d in genre_str for d in decade_genres):
        return "👴 The Boomer"

    # Count unique genres
    if len(set(genres)) > 8:
        return "🎭 The Chameleon"

    return "🎰 The Randomizer"


def compute_taste_score(
    mood: Dict[str, float],
    genres: List[str],
    top_artists: List[str],
    top_tracks: List[dict],
) -> Dict:
    """
    Compute a fun 'taste score' based purely on user's own data.
    Higher score = more 'interesting' taste (diverse, energetic, unique).
    """
    # Diversity score: more unique genres = better
    unique_genres = len(set(genres))
    diversity = min(unique_genres / 10, 1.0) * 100

    # Uniqueness score: less mainstream = more unique
    uniqueness = (1 - mood.get("mainstream", 0.5)) * 100

    # Energy score
    energy_score = mood.get("energy", 0.5) * 100

    # Consistency: how focused their taste is
    if top_artists:
        artist_counts = {}
        for t in top_tracks:
            for a in t.get("artists", []):
                artist_counts[a] = artist_counts.get(a, 0) + 1
        top_artist_dominance = max(artist_counts.values(), default=1) / max(len(top_tracks), 1)
        consistency = (1 - top_artist_dominance) * 100
    else:
        consistency = 50

    overall = round(
        diversity    * 0.35 +
        uniqueness   * 0.30 +
        energy_score * 0.20 +
        consistency  * 0.15,
        1
    )

    return {
        "overall":      overall,
        "diversity":    round(diversity,    1),
        "uniqueness":   round(uniqueness,   1),
        "energy_score": round(energy_score, 1),
        "consistency":  round(consistency,  1),
    }


def detect_intervention(top_artists: List[str], top_tracks: List[dict]) -> Dict:
    """Check if user is obsessed with one artist."""
    if not top_artists or not top_tracks:
        return {"needed": False}

    artist_counts: Dict[str, int] = {}
    for t in top_tracks:
        for a in t.get("artists", []):
            artist_counts[a] = artist_counts.get(a, 0) + 1

    if not artist_counts:
        return {"needed": False}

    top_artist = max(artist_counts, key=artist_counts.get)
    top_count  = artist_counts[top_artist]
    pct        = round(top_count / len(top_tracks) * 100)

    return {
        "needed":  pct >= 35,
        "artist":  top_artist,
        "pct":     pct,
        "message": f"You've listened to {top_artist} in {pct}% of your top tracks. This is not healthy.",
    }


def compute_squad_awards(members: List[Dict]) -> List[Dict]:
    """Assign funny awards to squad members based on their data."""
    if not members:
        return []

    awards = []

    # 👑 Music Overlord — highest taste score
    best = max(members, key=lambda m: m["scores"]["overall"])
    awards.append({"award": "👑 Music Overlord", "user": best["display_name"], "reason": f"Taste score: {best['scores']['overall']}"})

    # 💀 Needs Therapy — lowest valence
    saddest = min(members, key=lambda m: m["mood"]["valence"])
    awards.append({"award": "💀 Needs Therapy", "user": saddest["display_name"], "reason": f"Happiness score: {round(saddest['mood']['valence']*100)}%"})

    # 🤡 Spotify's Puppet — highest mainstream
    most_mainstream = max(members, key=lambda m: m["mood"]["mainstream"])
    awards.append({"award": "🤡 Spotify's Puppet", "user": most_mainstream["display_name"], "reason": f"Mainstream score: {round(most_mainstream['mood']['mainstream']*100)}%"})

    # 🧅 Too Cool For This — lowest mainstream
    most_unique = min(members, key=lambda m: m["mood"]["mainstream"])
    awards.append({"award": "🧅 Too Cool For This", "user": most_unique["display_name"], "reason": f"Uniqueness: {round((1-most_unique['mood']['mainstream'])*100)}%"})

    # 🔥 Hype Beast — highest energy
    most_energetic = max(members, key=lambda m: m["mood"]["energy"])
    awards.append({"award": "🔥 Hype Beast", "user": most_energetic["display_name"], "reason": f"Energy: {round(most_energetic['mood']['energy']*100)}%"})

    # 😴 Background Music — lowest energy
    most_chill = min(members, key=lambda m: m["mood"]["energy"])
    awards.append({"award": "😴 Background Music", "user": most_chill["display_name"], "reason": f"Energy: {round(most_chill['mood']['energy']*100)}%"})

    # 🌍 World Citizen — most diverse genres
    most_diverse = max(members, key=lambda m: len(set(m.get("genres", []))))
    awards.append({"award": "🌍 World Citizen", "user": most_diverse["display_name"], "reason": f"{len(set(most_diverse.get('genres', [])))} unique genres"})

    # 🔁 One-Trick Pony — most obsessed with one artist
    for m in members:
        if m.get("intervention", {}).get("needed"):
            awards.append({
                "award":  "🔁 One-Trick Pony",
                "user":   m["display_name"],
                "reason": m["intervention"]["message"],
            })
            break

    return awards
